sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9.0'

install:
- npm install i -g @angular/cli
- npm install i -g angular-cli-ghpages
- npm install
- ng build --prod --base-href "https://craigles.github.io/insultagram/"
- angular-cli-ghpages --no-silent --repo=https://GH_TOKEN@github.com/craigles/insultagram.git
